version: "2.4"

services:
  mongo:
    image: mongo:4
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - ../mongo:/data/db
      - ./dump:/dump
    ports:
      - "8051:27017"
