version: "2.4"

services:
  spa: 
    image: registry.gitlab.com/liveartdevteam/sandbox/trx0/admin-spa:0.1.0
    restart: on-failure:5
    ports:
      - "8052:80"
    environment:
      - VITE_VUE_APP_API_URL=http://localhost:8050
  api:
    image: registry.gitlab.com/liveartdevteam/sandbox/trx0/admin-api-boilerplate:0.0.2
    init: true
    restart: on-failure:5
    ports:
      - "8050:3000"
    environment:
      - NODE_ENV=production
      - DB_MONGO_URL=mongodb://mongo:27017/admin
    cpus: 0.4
    mem_limit: 300m
    mem_reservation: 100m
  mongo:
    image: mongo:4.0.1
    environment:
      - MONGO_INITDB_DATABASE=admin
    ports:
      - "8051:27017"
    volumes:
      - mongo-data:/data/db
volumes:
    mongo-data:
      